<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1">
<title>DVSFIFOInUseException class Reference</title>
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body bgcolor="#ffffff">
<!-- Generated by Doxygen 1.2.9.1 -->
<center>
<a class="qindex" href="main.html">Main Page</a> &nbsp; <a class="qindex" href="hierarchy.html">Class Hierarchy</a> &nbsp; <a class="qindex" href="annotated.html">Data Structures</a> &nbsp; <a class="qindex" href="files.html">File List</a> &nbsp; <a class="qindex" href="functions.html">Data Fields</a> &nbsp; </center>
<hr><h1>DVSFIFOInUseException  Class Reference</h1>FIFO already in use - unable to read This exception is thrown when attempting to read or write a FIFO that is already being used. 
<a href="#_details">More...</a>
<p>
<code>#include &lt;<a class="el" href="DVSClasses_8h-source.html">DVSClasses.h</a>&gt;</code>
<p>
<p>Inheritance diagram for DVSFIFOInUseException::
<p><center><img src="classDVSFIFOInUseException.gif" usemap="#DVSFIFOInUseException_map" border="0"></center>
<map name="DVSFIFOInUseException_map">
<area href="classDVSException.html" alt="DVSException" shape="rect" coords="0,56,153,80">
</map>
<table border=0 cellpadding=0 cellspacing=0>
<tr><td colspan=2><br><h2>Public Methods</h2></td></tr>
<tr><td nowrap align=right valign=top><a name="a0" doxytag="DVSFIFOInUseException::DVSFIFOInUseException"></a>
&nbsp;</td><td valign=bottom><b>DVSFIFOInUseException</b> (const char *context, std::exception *e)  throw ()</td></tr>
<tr><td nowrap align=right valign=top><a name="a1" doxytag="DVSFIFOInUseException::DVSFIFOInUseException"></a>
&nbsp;</td><td valign=bottom><b>DVSFIFOInUseException</b> (const DVSFIFOInUseException &amp;e)  throw ()</td></tr>
</table>
<hr><a name="_details"></a><h2>Detailed Description</h2>
FIFO already in use - unable to read This exception is thrown when attempting to read or write a FIFO that is already being used.
<p>
This might occur when calling FIFO_GetFrame when a background acquisition thread is running due to an earlier call to FIFO_BackgroundGetNextFrame <dl compact><dt>
Parameters: <dd>
<table border=0 cellspacing=2 cellpadding=0>
<tr><td valign=top><em>context
</em>&nbsp;</td><td>
Information on the context in which this exception is occurring - eg. the function call that caused it. NULL if no context string is required </td></tr>
<tr><td valign=top><em>e
</em>&nbsp;</td><td>
The causal parent exception of this one being instantiated. See <a class="el" href="classDVSException.html#b0">DVSException::DVSException</a>() </td></tr>
</table>
</dl>
<p>
<hr>The documentation for this class was generated from the following file:<ul>
<li><a class="el" href="DVSClasses_8h-source.html">DVSClasses.h</a></ul>
<HR>
<A HREF="mailto:matt.hammond@rd.bbc.co.uk">Matt Hammond</A> BBC R&D.
Class library documentation created using <A HREF="http://www.doxygen.org/">doxygen</a> documentation generator.
